name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Debug EC2_HOST
      run: echo "EC2_HOST is ${{ secrets.EC2_HOST }}"

    - name: Add EC2 host to known hosts
      run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Clean target directory on EC2
      run: ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo rm -rf /var/www/liza-pets/*'

    - name: Create tar archive
      run: tar -czf deploy.tar.gz *.html *.css *.mp3 img

    - name: Copy archive to EC2
      run: scp -i ~/.ssh/id_rsa deploy.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu

    - name: Extract the archive on EC2
      run: ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo tar -xzf /home/ubuntu/deploy.tar.gz -C /var/www/liza-pets'
